package ui.MainMenu;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Toled
 * @param <V>
 */
public class WaitingRoomJPanel extends javax.swing.JPanel {

    private MainMenuView view;
    private WaitingRoomDTO waitingRoom;

    /**
     * Creates new form LobbyJPanel.
     */
    public WaitingRoomJPanel() {
        initComponents();
    }

    public void setView(MainMenuView view) {
        this.view = view;
    }

    public void updateWaitingRoom(MainMenuViewModel viewModel) {
        this.waitingRoom = viewModel.getWaitingRoom();
        setPlayers();

    }

    private void setPlayers() {
        List<JButton> buttons = new ArrayList<>();
        buttons.add(this.btnAvatar1);
        buttons.add(this.btnAvatar2);
        buttons.add(this.btnAvatar3);
        buttons.add(this.btnAvatar4);

        List<JLabel> labels = new ArrayList<>();
        labels.add(this.lblAvatar1);
        labels.add(this.lblAvatar2);
        labels.add(this.lblAvatar3);
        labels.add(this.lblAvatar4);

        for (int i = 0; i < buttons.size(); i++) {
            if (i >= waitingRoom.getPlayers().size()) {
                labels.get(i).setText("?");
                buttons.get(i).setText("?");
            } else {
                labels.get(i).setText(this.waitingRoom.getPlayers().get(i).getAvatar().getNombre());
                buttons.get(i).setText(this.waitingRoom.getPlayers().get(i).getAvatar().getImage());

            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("all")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLeave = new javax.swing.JButton();
        btnAvatar2 = new javax.swing.JButton();
        btnReady = new javax.swing.JButton();
        btnAvatar3 = new javax.swing.JButton();
        btnAvatar4 = new javax.swing.JButton();
        btnAvatar1 = new javax.swing.JButton();
        lblAvatar4 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblAvatar1 = new javax.swing.JLabel();
        lblAvatar2 = new javax.swing.JLabel();
        lblAvatar3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 204));
        setPreferredSize(new java.awt.Dimension(1280, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLeave.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 36)); // NOI18N
        btnLeave.setForeground(new java.awt.Color(0, 153, 153));
        btnLeave.setText("LEAVE");
        btnLeave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLeave.setBorderPainted(false);
        btnLeave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btnLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 260, 80));

        btnAvatar2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        btnAvatar2.setForeground(new java.awt.Color(0, 153, 153));
        btnAvatar2.setText("AvatarsAASD");
        btnAvatar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAvatar2.setBorderPainted(false);
        btnAvatar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btnAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 130, 130));

        btnReady.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 36)); // NOI18N
        btnReady.setForeground(new java.awt.Color(0, 153, 153));
        btnReady.setText("READY");
        btnReady.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReady.setBorderPainted(false);
        btnReady.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadyActionPerformed(evt);
            }
        });
        add(btnReady, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 600, 240, 80));

        btnAvatar3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        btnAvatar3.setForeground(new java.awt.Color(0, 153, 153));
        btnAvatar3.setText("AvatarsAASD");
        btnAvatar3.setBorder(null);
        btnAvatar3.setBorderPainted(false);
        btnAvatar3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btnAvatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 130, 130));

        btnAvatar4.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        btnAvatar4.setForeground(new java.awt.Color(0, 153, 153));
        btnAvatar4.setText("AvatarsAASD");
        btnAvatar4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAvatar4.setBorderPainted(false);
        btnAvatar4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btnAvatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, 130, 130));

        btnAvatar1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        btnAvatar1.setForeground(new java.awt.Color(0, 153, 153));
        btnAvatar1.setText("AvatarsAASD");
        btnAvatar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAvatar1.setBorderPainted(false);
        btnAvatar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btnAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 130, 130));

        lblAvatar4.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        lblAvatar4.setForeground(new java.awt.Color(0, 153, 153));
        lblAvatar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblAvatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 320, 130, 20));

        lblTitle.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle.setText("WAITING FOR PLAYERS...");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 530, 70));

        lblAvatar1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        lblAvatar1.setForeground(new java.awt.Color(0, 153, 153));
        lblAvatar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 130, 20));

        lblAvatar2.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        lblAvatar2.setForeground(new java.awt.Color(0, 153, 153));
        lblAvatar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 130, 20));

        lblAvatar3.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        lblAvatar3.setForeground(new java.awt.Color(0, 153, 153));
        lblAvatar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblAvatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 130, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadyActionPerformed
    
        view.foreStart();
        
        
    }//GEN-LAST:event_btnReadyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvatar1;
    private javax.swing.JButton btnAvatar2;
    private javax.swing.JButton btnAvatar3;
    private javax.swing.JButton btnAvatar4;
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton btnReady;
    private javax.swing.JLabel lblAvatar1;
    private javax.swing.JLabel lblAvatar2;
    private javax.swing.JLabel lblAvatar3;
    private javax.swing.JLabel lblAvatar4;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
