package ui.MainMenu;

import domain.DominoGame;
import dtos.PlayerDTO;
import dtos.WaitingRoomDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 * Panel que representa la sala de espera donde los jugadores pueden esperar a
 * que comience el juego.
 */
public class WaitingRoomJPanel extends javax.swing.JPanel implements ViewParent {

    private MainMenuView view;
    private WaitingRoomDTO waitingRoom;
    private MainMenuPresenter presenter;
    private boolean isAdmin = false;

    /**
     * Crea un nuevo panel de sala de espera.
     */
    public WaitingRoomJPanel() {
        initComponents();
    }

    /**
     * Establece la vista asociada a este panel.
     *
     * @param view La vista asociada.
     */
    public void setView(MainMenuView view) {
        this.view = view;
    }

    /**
     * Actualiza la sala de espera con la información proporcionada por el
     * modelo de vista.
     *
     * @param viewModel El modelo de vista que contiene la información de la
     * sala de espera.
     */
    public void updateWaitingRoom(MainMenuViewModel viewModel) {
        this.waitingRoom = viewModel.getWaitingRoom();
        this.isAdmin(viewModel.isAdmin());

        for (PlayerDTO p : this.waitingRoom.getPlayers()) {
            System.out.println("Este jugador esta ready:" + p.isIsReady());
        }

        System.out.println("Validacion 1 de iniciar partida:");
        System.out.println("Soy Admin:" + viewModel.isAdmin() + " y todos estan listos " + viewModel.startGame());

        System.out.println("Validacion 2 de iniciar partida:");
        System.out.println("Soy Admin:" + viewModel.isAdmin() + " y esta llena la lsista " + (waitingRoom.getPlayers().size() == 4));

        if (viewModel.isAdmin() && viewModel.startGame() || viewModel.isAdmin() && waitingRoom.getPlayers().size() == 4) {
            int cantTiles = this.tilesNum.getSelectedIndex() + 2;
            this.waitingRoom.setInitialTiles(cantTiles);
            System.out.println("PROCEDE A INICIAR LA PARTIDA");
            this.presenter.start(waitingRoom);
        }
        setPlayers();
    }

    /**
     * Oculta o muestra los elementos específicos para el administrador.
     *
     * @param isAdmin true si el jugador es un administrador, false de lo
     * contrario.
     */
    private void isAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
        this.tilesNum.setVisible(isAdmin);
        this.tilesNumText.setVisible(isAdmin);
    }

    /**
     * Configura la visualización de los jugadores en el panel.
     */
    private void setPlayers() {

        List<JButton> buttons = new ArrayList<>();
        buttons.add(this.btnAvatar1);
        buttons.add(this.btnAvatar2);
        buttons.add(this.btnAvatar3);
        buttons.add(this.btnAvatar4);

        List<JLabel> labels = new ArrayList<>();
        labels.add(this.lblAvatar1);
        labels.add(this.lblAvatar2);
        labels.add(this.lblAvatar3);
        labels.add(this.lblAvatar4);

        for (int i = 0; i < buttons.size(); i++) {
            if (i >= waitingRoom.getPlayers().size()) {
                labels.get(i).setText("?");
                buttons.get(i).setText("?");
            } else {
                labels.get(i).setText(this.waitingRoom.getPlayers().get(i).getAvatar().getNombre());
                buttons.get(i).setText(this.waitingRoom.getPlayers().get(i).getAvatar().getImage());

            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("all")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLeave = new javax.swing.JButton();
        btnAvatar2 = new javax.swing.JButton();
        btnReady = new javax.swing.JButton();
        btnAvatar3 = new javax.swing.JButton();
        btnAvatar4 = new javax.swing.JButton();
        btnAvatar1 = new javax.swing.JButton();
        lblAvatar4 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblAvatar1 = new javax.swing.JLabel();
        lblAvatar2 = new javax.swing.JLabel();
        lblAvatar3 = new javax.swing.JLabel();
        tilesNum = new javax.swing.JComboBox<>();
        tilesNumText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 204));
        setPreferredSize(new java.awt.Dimension(1280, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLeave.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 36)); // NOI18N
        btnLeave.setForeground(new java.awt.Color(0, 153, 153));
        btnLeave.setText("LEAVE");
        btnLeave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLeave.setBorderPainted(false);
        btnLeave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveActionPerformed(evt);
            }
        });
        add(btnLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 260, 80));

        btnAvatar2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        btnAvatar2.setForeground(new java.awt.Color(0, 153, 153));
        btnAvatar2.setText("AvatarsAASD");
        btnAvatar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAvatar2.setBorderPainted(false);
        btnAvatar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAvatar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvatar2ActionPerformed(evt);
            }
        });
        add(btnAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 130, 130));

        btnReady.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 36)); // NOI18N
        btnReady.setForeground(new java.awt.Color(0, 153, 153));
        btnReady.setText("READY");
        btnReady.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReady.setBorderPainted(false);
        btnReady.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadyActionPerformed(evt);
            }
        });
        add(btnReady, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 600, 240, 80));

        btnAvatar3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        btnAvatar3.setForeground(new java.awt.Color(0, 153, 153));
        btnAvatar3.setText("AvatarsAASD");
        btnAvatar3.setBorder(null);
        btnAvatar3.setBorderPainted(false);
        btnAvatar3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btnAvatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 130, 130));

        btnAvatar4.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        btnAvatar4.setForeground(new java.awt.Color(0, 153, 153));
        btnAvatar4.setText("AvatarsAASD");
        btnAvatar4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAvatar4.setBorderPainted(false);
        btnAvatar4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btnAvatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, 130, 130));

        btnAvatar1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        btnAvatar1.setForeground(new java.awt.Color(0, 153, 153));
        btnAvatar1.setText("AvatarsAASD");
        btnAvatar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAvatar1.setBorderPainted(false);
        btnAvatar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btnAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 130, 130));

        lblAvatar4.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        lblAvatar4.setForeground(new java.awt.Color(0, 153, 153));
        lblAvatar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblAvatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 320, 130, 20));

        lblTitle.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle.setText("WAITING FOR PLAYERS...");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 530, 70));

        lblAvatar1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        lblAvatar1.setForeground(new java.awt.Color(0, 153, 153));
        lblAvatar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 130, 20));

        lblAvatar2.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        lblAvatar2.setForeground(new java.awt.Color(0, 153, 153));
        lblAvatar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 130, 20));

        lblAvatar3.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        lblAvatar3.setForeground(new java.awt.Color(0, 153, 153));
        lblAvatar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblAvatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 130, 20));

        tilesNum.setBackground(new java.awt.Color(153, 204, 255));
        tilesNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 Fichas", "3 Fichas", "4 Fichas", "5 Fichas", "6 Fichas", "7 Fichas" }));
        tilesNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tilesNumActionPerformed(evt);
            }
        });
        add(tilesNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, -1));

        tilesNumText.setBackground(new java.awt.Color(255, 204, 204));
        tilesNumText.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tilesNumText.setText("Numero de fichas inciales:");
        add(tilesNumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 160, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadyActionPerformed
        presenter.setMyPlayerReady();

    }//GEN-LAST:event_btnReadyActionPerformed

    private void tilesNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tilesNumActionPerformed
        // minimo de 2 fichas a elegir maximo de 7
        // settear a la waitingroomDTO

        //waitingRoom.setInitialTiles(tilesNum.getSelectedIndex() + 1);
    }//GEN-LAST:event_tilesNumActionPerformed

    private void btnAvatar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvatar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAvatar2ActionPerformed

    private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveActionPerformed
        this.presenter.playerLeaves();
        this.view.close();


    }//GEN-LAST:event_btnLeaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvatar1;
    private javax.swing.JButton btnAvatar2;
    private javax.swing.JButton btnAvatar3;
    private javax.swing.JButton btnAvatar4;
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton btnReady;
    private javax.swing.JLabel lblAvatar1;
    private javax.swing.JLabel lblAvatar2;
    private javax.swing.JLabel lblAvatar3;
    private javax.swing.JLabel lblAvatar4;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JComboBox<String> tilesNum;
    private javax.swing.JLabel tilesNumText;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setPresenter(MainMenuPresenter presenter) {
        this.presenter = presenter;
    }

}
